### ISSUE TITLE
The mod dont work in the update skills 2.0

### ISSUE THREAD

**Issue by pO0P3R125** [xiaoxiao921/ItemLib#10]

**Comment by xiaoxiao921** [comment]
Hi, ItemLib will be integrated directly into R2API soon. I'll let you know when that happens

**Comment by xiaoxiao921** [comment]
ItemLib has been integrated into R2API, its available for downloading here :
https://thunderstore.io/package/tristanmcpherson/R2API/
i'll close this issue and archive the repo as it will not receive any more update
