### ISSUE TITLE
ItemLib makes item model disappeared and the VFX of item droping become strange

### ISSUE THREAD

**Issue by PotterLee694** [xiaoxiao921/ItemLib#2]
Only R2API and ItemLib （momomed and plugin）installed.
1、出生舱的燃料电池被替换成攻速针了。
2、所有物品的模型都看不到了
3、物品掉落动画（光球）变得很诡异，落地后依然运动并且偏离物品实际位置。

看大佬名字像是国人，先写中文试试吧（滑稽）

**Comment by xiaoxiao921** [comment]
Hi, i'm not actually Chinese haha.
ItemLib isn't updated for the latest update (scorched acres update)
I will update it when r2API will be updated in thunderstore.io :)
