### ISSUE TITLE
Cant pass profile creation screen

### ISSUE THREAD

**Issue by muhamvv** [xiaoxiao921/ItemLib#5]
I just installed the mod following the instructions, but it refuses to let me pass profile creation menu.

**Comment by xiaoxiao921** [comment]
Please give me a full log of the console when that happens and copy paste it in there
https://pastebin.com

**Comment by muhamvv** [comment]
that from badprofiles
https://pastebin.com/zbXCQZZF

that from BeplnEx LogOutput
https://pastebin.com/Ty9TfL4N

**Comment by xiaoxiao921** [comment]
Sorry but I need a **full** log of the console when this happens, if you don't know how to copy paste directly from console, please find the output_log.txt file that should be located in this folder (copy paste this line and open it from the Windows File Explorer or by using WIN+R keyboard shortcut :
`%AppData%\..\LocalLow\Hopoo Games, LLC\Risk of Rain 2\output_log.txt`

**Comment by muhamvv** [comment]
I somehow fixed it(reinstalled everything) and now all works.
